#include "GameConfig.h"

__uint32 CONFIG::MAX_PLAYER_NUMBER = 20;
__uint32 CONFIG::MAX_ROOM_NUMBER = 5;
__uint32 CONFIG::MAX_ROOM_PLAYER = 2;

__uint32 CONFIG::SOCK_SEND_TIME_LIMIT = 500;
__uint32 CONFIG::SOCK_RECV_TIME_LIMIT = 500;
__uint32 CONFIG::SOCKET_TO_SYSTEM_TEMP = 0;
__uint32 CONFIG::SYSTEM_TO_SOCKET_TEMP = 0;
__uint32 CONFIG::HEARTBEAT_MECHANISM = 1;
__uint32 CONFIG::HEARTBEAT_CHECK_INTERVAL = 60;
__uint32 CONFIG::HEARTBEAT_CHECK_NUMBER = 3;

__uint32 CONFIG::PORT = 30000;//端口号
